server:
  port: 8888
spring:
  application:
    name: nft
  swagger:
    enabled: true      
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:192.168.1.60}:${DATABASE_PORT:3306}/${DATABASE_NAME:cdc}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 
logging:
  level:
    org.inlighting.mapper: debug                 
